security.jwt.token.secret-key: cd62267c14d7348a17465b3e7b6f1ea598901fc29b8902aabde35bcab75759a4

spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yourdb?serverTimezone=UTC&useSSL=false
    username: root
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update

logging.level.org.springframework.web: DEBUG

